[versions]
kotlin-general = "1.7.10"
kotlin-coroutines = "1.6.4"

android-gradle = "7.2.2"
android-activity = "1.3.1"

material = "1.6.1"
activity = "1.3.1"
androidx-core-version = "1.9.0"

lifecycle = "2.5.1"

compose = "1.2.1"
compose-compiler = "1.3.2"
compose-accompanist = "0.25.1"
compose-constraint = "1.0.1"
compose-navigation = "2.5.1"

maps-compose = "2.7.0"
maps = "18.1.0"
# play-services
ps-location = "20.0.0"

serialization-json = "1.4.0"

ktor = "2.1.0"
koin = "3.2.0"
okhttp = "4.10.0"
room = "2.4.3"
navigation = "2.5.2"
coil = "2.2.1"
dialogs = "0.8.1-rc"

appcompat = "1.5.1"
fragment = "1.5.2"


[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

kotlin-serialization-gradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-general" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }

android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-version" }
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
android-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }

# UI
material = { module = "com.google.android.material:material", version.ref = "material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "compose-accompanist" }
compose-accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "compose-accompanist" }
compose-accompanist-pagerindicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "compose-accompanist" }
compose-accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "compose-accompanist" }
compose-accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "compose-accompanist" }
compose-accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "compose-accompanist" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-dialogs = { module = "io.github.vanpra.compose-material-dialogs:core", version.ref = "dialogs" }
compose-time-dialog = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "dialogs" }

googlemaps-common = { module = "com.google.android.gms:play-services-maps", version.ref = "maps" }
play-location = { module = "com.google.android.gms:play-services-location", version.ref = "ps-location" }
googlemaps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps-compose" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-nav = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-sockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android-gradle" }
android-lib = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-general" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-general" }
